# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  issues: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Create Issue on Failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          const title = `Build/Test Failure - ${context.workflow} #${context.runNumber}`;
          const body = `
          ## Build/Test Failure Report
          
          **Workflow:** ${context.workflow}
          **Run Number:** ${context.runNumber}
          **Branch:** ${context.ref}
          **Commit:** ${context.sha}
          **Actor:** ${context.actor}
          **Event:** ${context.eventName}
          
          **Failure Details:**
          - **Repository:** ${context.repo.owner}/${context.repo.repo}
          - **Workflow Run:** [View Details](${context.payload.repository.html_url}/actions/runs/${context.runId})
          
          **Next Steps:**
          1. Review the workflow logs for detailed error information
          2. Fix the failing build/test issues
          3. Close this issue once resolved
          
          **Auto-generated by GitHub Actions**
          `;
          
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: title,
            body: body,
            labels: ['bug', 'ci/cd', 'auto-generated']
          });
